### ISSUE TITLE
DuckPAN fails to install on Arch linux (Exit status 29)

### ISSUE THREAD

**Issue by WesleyAC** [duckduckgo/p5-duckpan-installer#2]
Hi,

I ran install.pl, but it threw an error.
The build.log is at https://gist.github.com/WesleyAC/7421059
I ran it a second time, but got the same result.

Any idea what I can do to make this work?  I understand that Arch isn't officially supported, but it says that it has been able to work on Arch.  What should I do to get it to work?

Thanks,
Wesley.

**Comment by moollaza** [comment]
Closing. Very old issue -- looks like the problem was a [lack of memory](https://gist.github.com/WesleyAC/7421059#file-build-log-L158)?
